### ISSUE TITLE
PelePhysics Reorganization

### ISSUE THREAD

**Issue by baperry2** [AMReX-Combustion/PelePhysics#446]
The overall goal here is to simplify the code which is currently split across too many individual repos in this organization. Most stuff from PeleMP and PeleRad will be pulled into PelePhysics, with the test cases going to their respective codes (C or LMeX).

- [x] Move Filter Utility from PeleC to PelePhysics/Utility - @baperry2 PR #445 
- [x] Add AMReX and Sundials Submodules to PelePhysics/Submodules - @baperry2  PR #451 
- [x] Move PeleMP Utils to PelePhysics/Support - @marchdf  PR #443 
- [x] Move PeleMP Source to PelePhysics/Source - @marchdf PR #448 
- [x] Move PeleMP Docs to PelePhysics/Docs - @marchdf PR #449 
- [x] Merge Radiation PR for PeleLMeX - PR https://github.com/AMReX-Combustion/PeleLMeX/pull/313 
- [x] Move EOS Transport Reactions Utility to PelePhysics/Source; Support/Mechanism/Models to PelePhysics/Mechanisms @marchdf PR #452 
- [x] Update PeleLMeX with above PelePhysics changes @baperry2 https://github.com/AMReX-Combustion/PeleLMeX/pull/325
- [x] Update PeleC with above PelePhysics changes @marchdf PR https://github.com/AMReX-Combustion/PeleC/pull/715

--- Barrier ------

- [ ] Move PeleMP Exec cases to PeleC/PeleLMeX
    - [x] PeleLM: deprecated
    - [x] PeleC: move cases @marchdf https://github.com/AMReX-Combustion/PeleC/pull/724
    - [x] PeleC: add cases to CI (as relevant): not doing, we already have a spray and soot case
    - [x] PeleLMeX: move cases
    - [ ] PeleLMeX: add cases to CI (as relevant)
 - [x] Fix the prob_parm passing into Spray stuff @marchdf PR https://github.com/AMReX-Combustion/PelePhysics/pull/462 and https://github.com/AMReX-Combustion/PeleC/pull/730
 - [x] Move PeleRad Source to PelePhysics
    - [x] Move code
    - [x] Harmonize with existing code
- [ ] Unify all python scripts with one poetry environment
- [x] Archive PeleLM and other no longer used repos

Documentation tasks no longer part of this issue, now broken out into #460
